# ref: https://docs.travis-ci.com/user/languages/python

sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install tox-travis
  - pip install python-coveralls
script: tox
after_success:
  - coveralls
